### ISSUE TITLE
Can't build it manually

### ISSUE THREAD

**Issue by gandarez** [devgianlu/processing-wakatime#3]
I tried to build it manully using the source code by running `mvn clean package` and got the error below:
![Screen Shot 2021-01-18 at 15 11 45](https://user-images.githubusercontent.com/782854/104950523-d04f0600-598e-11eb-8154-0a2c1bbb5e78.png)

**Comment by devgianlu** [comment]
It looks like they disappeared from Maven, no idea why. Will try to find a solution.

**Comment by gandarez** [comment]
No worries. Just one question. I'm trying to load this plugin into Arduino IDE which basically is a Processing IDE. However it breaks while loading and no log is showed. Have you ever tried it? That's the reason I need to build it manually and try to use that build.

```
java.lang.AbstractMethodError
	at processing.app.Editor.addTools(Editor.java:885)
	at processing.app.Editor.buildToolsMenu(Editor.java:732)
	at processing.app.Editor.buildMenuBar(Editor.java:544)
	at processing.app.Editor.<init>(Editor.java:291)
	at processing.app.Base.handleOpen(Base.java:889)
	at processing.app.Base.handleOpen(Base.java:875)
	at processing.app.Base.handleOpen(Base.java:871)
	at processing.app.Base.handleNew(Base.java:810)
	at processing.app.Base.<init>(Base.java:498)
	at processing.app.Base.main(Base.java:150)
```
https://forum.arduino.cc/index.php?topic=578486.0

**Comment by devgianlu** [comment]
Never tried to run it on the Arduino IDE. The error looks strange because [addTools](https://github.com/arduino/Arduino/blob/f4e8a91f101773c47481ae5444e7b4e32ddda0a4/app/src/processing/app/Editor.java#L808) doesn't seem to be abstract, but the docs say:

> Thrown when an application tries to call an abstract method. Normally, this error is caught by the compiler; this error can only occur at run time if the definition of some class has incompatibly changed since the currently executing method was last compiled.

Which makes sense because Arduino seems to have "forked" the `processing.app` package instead of referencing the JAR: https://github.com/arduino/Arduino/tree/master/app/src/processing/app

**Comment by gandarez** [comment]
Do you have any idea how to fix it? Any advice for me on how to start debugging it?

**Comment by devgianlu** [comment]
Does the Arduino IDE install folder contain an `app.jar` file? I believe the Processing IDE does, you could use that to replace the one that's missing from Maven.
